var ItemHelper = Games.ItemHelper;
var TimeHelper = Games.TimeHelper;
var MeetingPanelType = Games.MeetingPanelType;
var MeetingRewardType = Games.MeetingRewardType;
var MeetingMarkUpType = Games.MeetingMarkUpType;
var MeetingResultType = Games.MeetingResultType;
var Signal = signals.Signal;
var TypedSignal = signals.TypedSignal;
var Bindable = signals.Bindable;
var GuideDialogType = Games.GuideDialogType;
//# sourceMappingURL=GlobalIncludes.js.map