/////////////////////////////////////
// ihaiu.GenerateFguiResPackageConfig生成
// http://blog.ihaiu.com
/////////////////////////////////////
var Games;
(function (Games) {
    // =====================
    // fgui包资源配置列表
    // ---------------------
    var GuiResPackageConfigReader = /** @class */ (function () {
        function GuiResPackageConfigReader() {
            // 字典
            this.dict = new Dictionary();
        }
        // 添加配置
        GuiResPackageConfigReader.prototype.addconfig = function (config) {
            this.dict.add(config.packageName, config);
        };
        // 获取配置
        GuiResPackageConfigReader.prototype.getconfig = function (packageName) {
            return this.dict.getValue(packageName);
        };
        // 初始化
        GuiResPackageConfigReader.prototype.install = function () {
            var config;
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "Activity";
            config.resBin = "Activity.bin";
            config.resAtlas.push("Activity@atlas0.png");
            config.resAtlas.push("Activity@atlas_ac07l.png");
            config.resAtlas.push("Activity@atlas_ac07m.png");
            config.resAtlas.push("Activity@atlas_f9f11d.png");
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "ArtistDic";
            config.resBin = "ArtistDic.bin";
            config.resAtlas.push("ArtistDic@atlas0.png");
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "Bag";
            config.resBin = "Bag.bin";
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "Building";
            config.resBin = "Building.bin";
            config.resAtlas.push("Building@atlas0.png");
            config.resAtlas.push("Building@atlas0_1.png");
            config.resAtlas.push("Building@atlas_cpc911l.png");
            config.resAtlas.push("Building@atlas_dyfe120.png");
            config.resAtlas.push("Building@atlas_iacm12l.png");
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "Common";
            config.resBin = "Common.bin";
            config.resAtlas.push("Common@atlas0.png");
            config.resAtlas.push("Common@atlas0_1.png");
            config.resAtlas.push("Common@atlas0_2.png");
            config.resAtlas.push("Common@atlas0_3.png");
            config.resAtlas.push("Common@atlas0_4.png");
            config.resAtlas.push("Common@atlas0_5.png");
            config.resAtlas.push("Common@atlas2.png");
            config.resAtlas.push("Common@atlas_dm31t22d.png");
            config.resAtlas.push("Common@atlas_hh765m.png");
            config.resAtlas.push("Common@atlas_hh765n.png");
            config.resAtlas.push("Common@atlas_hh7681.png");
            config.resAtlas.push("Common@atlas_hh7688.png");
            config.resAtlas.push("Common@atlas_i4hgt240.png");
            config.resAtlas.push("Common@atlas_jmopn4.png");
            config.resAtlas.push("Common@atlas_l7rut207.png");
            config.resAtlas.push("Common@atlas_m9lgt21y.png");
            config.resAtlas.push("Common@atlas_m9lgt21z.png");
            config.resAtlas.push("Common@atlas_m9lgt220.png");
            config.resAtlas.push("Common@atlas_m9lgt221.png");
            config.resAtlas.push("Common@atlas_mu1z2k.png");
            config.resAtlas.push("Common@atlas_s9dx1g.png");
            config.resAtlas.push("Common@atlas_s9dx1h.png");
            config.resAtlas.push("Common@atlas_s9dx1i.png");
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "Cooperation";
            config.resBin = "Cooperation.bin";
            config.resAtlas.push("Cooperation@atlas0.png");
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "FilmScreenAnim1";
            config.resBin = "FilmScreenAnim1.bin";
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "FilmScreenAnim2";
            config.resBin = "FilmScreenAnim2.bin";
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "FilmScreenCommon";
            config.resBin = "FilmScreenCommon.bin";
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "Fx";
            config.resBin = "Fx.bin";
            config.resAtlas.push("Fx@atlas0.png");
            config.resAtlas.push("Fx@atlas0_1.png");
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "GM";
            config.resBin = "GM.bin";
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "Guide";
            config.resBin = "Guide.bin";
            config.resAtlas.push("Guide@atlas0.png");
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "LangEn";
            config.resBin = "LangEn.bin";
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "LangZhCn";
            config.resBin = "LangZhCn.bin";
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "Login";
            config.resBin = "Login.bin";
            config.resAtlas.push("Login@atlas0.png");
            config.resAtlas.push("Login@atlas_8zgr15.png");
            config.resAtlas.push("Login@atlas_dk944n.png");
            config.resAtlas.push("Login@atlas_dk944o.png");
            config.resAtlas.push("Login@atlas_dk944t.png");
            config.resAtlas.push("Login@atlas_l1hm4w.png");
            config.resAtlas.push("Login@atlas_l1hm4x.png");
            config.resAtlas.push("Login@atlas_l1hm4y.png");
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "MainUI";
            config.resBin = "MainUI.bin";
            config.resAtlas.push("MainUI@atlas0.png");
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "Manage";
            config.resBin = "Manage.bin";
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "Market";
            config.resBin = "Market.bin";
            config.resAtlas.push("Market@atlas0.png");
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "Mission";
            config.resBin = "Mission.bin";
            config.resAtlas.push("Mission@atlas0.png");
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "Notice";
            config.resBin = "Notice.bin";
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "Oscar";
            config.resBin = "Oscar.bin";
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "PfSkin";
            config.resBin = "PfSkin.bin";
            config.resAtlas.push("PfSkin@atlas0.png");
            config.resAtlas.push("PfSkin@atlas0_1.png");
            config.resAtlas.push("PfSkin@atlas_dk94t21h.png");
            config.resAtlas.push("PfSkin@atlas_iacmt1w7.png");
            config.resAtlas.push("PfSkin@atlas_l7rut1z7.png");
            config.resAtlas.push("PfSkin@atlas_l7rut1z9.png");
            config.resAtlas.push("PfSkin@atlas_sm6tt1ve.png");
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "PlayerInfo";
            config.resBin = "PlayerInfo.bin";
            config.resAtlas.push("PlayerInfo@atlas0.png");
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "Produce";
            config.resBin = "Produce.bin";
            config.resAtlas.push("Produce@atlas0.png");
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "Rank";
            config.resBin = "Rank.bin";
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "Sound";
            config.resBin = "Sound.bin";
            config.sounds.push("Sound@8z3l2h.wav");
            config.sounds.push("Sound@8z3l2i.wav");
            config.sounds.push("Sound@8z3l2j.wav");
            config.sounds.push("Sound@8z3l2k.wav");
            config.sounds.push("Sound@8z3l2l.wav");
            config.sounds.push("Sound@8z3l2m.wav");
            config.sounds.push("Sound@8z3l2n.wav");
            config.sounds.push("Sound@o3172q.wav");
            config.sounds.push("Sound@o3172r.wav");
            config.sounds.push("Sound@o3172s.wav");
            config.sounds.push("Sound@q9mu2o.wav");
            config.sounds.push("Sound@q9mu2p.wav");
            config.sounds.push("Sound@s3xz1n.mp3");
            config.sounds.push("Sound@s3xz1o.mp3");
            config.sounds.push("Sound@s3xz1p.mp3");
            config.sounds.push("Sound@s3xz1q.wav");
            config.sounds.push("Sound@s3xz1r.wav");
            config.sounds.push("Sound@s3xz1s.wav");
            config.sounds.push("Sound@s3xz1t.wav");
            config.sounds.push("Sound@s3xz1u.wav");
            config.sounds.push("Sound@s3xz1v.wav");
            config.sounds.push("Sound@s3xz1w.wav");
            config.sounds.push("Sound@s3xz1x.wav");
            config.sounds.push("Sound@s3xz1y.wav");
            config.sounds.push("Sound@s3xz1z.wav");
            config.sounds.push("Sound@s3xz20.wav");
            config.sounds.push("Sound@s3xz21.wav");
            config.sounds.push("Sound@s3xz22.wav");
            config.sounds.push("Sound@s3xz23.wav");
            config.sounds.push("Sound@s3xz24.wav");
            config.sounds.push("Sound@s3xz25.wav");
            config.sounds.push("Sound@s3xz26.wav");
            config.sounds.push("Sound@s3xz27.wav");
            config.sounds.push("Sound@s3xz28.wav");
            config.sounds.push("Sound@s3xz29.wav");
            config.sounds.push("Sound@s3xz2a.wav");
            config.sounds.push("Sound@s3xz2b.wav");
            config.sounds.push("Sound@s3xz2c.wav");
            config.sounds.push("Sound@s3xz2d.wav");
            config.sounds.push("Sound@s3xz2e.wav");
            config.sounds.push("Sound@s3xz2f.wav");
            config.sounds.push("Sound@s3xz2g.wav");
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "Street";
            config.resBin = "Street.bin";
            config.resAtlas.push("Street@atlas0.png");
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "System";
            config.resBin = "System.bin";
            config.resAtlas.push("System@atlas0.png");
            config.resAtlas.push("System@atlas_5sasa.png");
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "SystemSettings";
            config.resBin = "SystemSettings.bin";
            config.resAtlas.push("SystemSettings@atlas0.png");
            this.addconfig(config);
            config = new Games.GuiResPackageConfig();
            config.resDir = "fgui";
            config.packageName = "WarMovie";
            config.resBin = "WarMovie.bin";
            config.resAtlas.push("WarMovie@atlas0.png");
            config.resAtlas.push("WarMovie@atlas0_1.png");
            config.resAtlas.push("WarMovie@atlas_lsbtdw.png");
            config.resAtlas.push("WarMovie@atlas_qbxl8s.png");
            config.resAtlas.push("WarMovie@atlas_qbxl8t.png");
            config.resAtlas.push("WarMovie@atlas_qbxl8u.png");
            config.resAtlas.push("WarMovie@atlas_qbxl8v.png");
            config.resAtlas.push("WarMovie@atlas_qbxl8w.png");
            config.resAtlas.push("WarMovie@atlas_qbxl93.png");
            config.resAtlas.push("WarMovie@atlas_r0zd1e.png");
            config.resAtlas.push("WarMovie@atlas_r0zd1f.png");
            config.resAtlas.push("WarMovie@atlas_r0zd1g.png");
            config.resAtlas.push("WarMovie@atlas_r0zd1x.png");
            config.resAtlas.push("WarMovie@atlas_r0zd3p.png");
            this.addconfig(config);
        };
        return GuiResPackageConfigReader;
    }());
    Games.GuiResPackageConfigReader = GuiResPackageConfigReader;
})(Games || (Games = {}));
//# sourceMappingURL=GuiResPackageConfigReader.js.map