/////////////////////////////////////
// ihaiu.ExportFairyGUICode生成
// http://blog.ihaiu.com
/////////////////////////////////////
var fgui;
(function (fgui) {
    var WarMovie;
    (function (WarMovie) {
        var WarMovieBinder = /** @class */ (function () {
            function WarMovieBinder() {
            }
            WarMovieBinder.bindAll = function () {
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarPaishequeren.URL, WarMovie.WarPaishequeren);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarCostView.URL, WarMovie.WarCostView);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.CloseBtn.URL, WarMovie.CloseBtn);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilmStar.URL, WarMovie.WarFilmStar);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.Star.URL, WarMovie.Star);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarYRCostItem.URL, WarMovie.WarYRCostItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.ConfirmBtn.URL, WarMovie.ConfirmBtn);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarYRForFilm.URL, WarMovie.WarYRForFilm);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.Warbubble.URL, WarMovie.Warbubble);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarYRFilmItem.URL, WarMovie.WarYRFilmItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilming.URL, WarMovie.WarFilming);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.FilmProgress.URL, WarMovie.FilmProgress);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.FilmingTip.URL, WarMovie.FilmingTip);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarMoveTextUD.URL, WarMovie.WarMoveTextUD);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilmTypeItem.URL, WarMovie.WarFilmTypeItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilmSelecting.URL, WarMovie.WarFilmSelecting);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarPeople.URL, WarMovie.WarPeople);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.FilmIcon.URL, WarMovie.FilmIcon);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarPeopleSmall.URL, WarMovie.WarPeopleSmall);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.FilmSelectItem.URL, WarMovie.FilmSelectItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilmingYRItem.URL, WarMovie.WarFilmingYRItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilmingSelectTipItem.URL, WarMovie.WarFilmingSelectTipItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilmInfo.URL, WarMovie.WarFilmInfo);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.CompletedConditions.URL, WarMovie.CompletedConditions);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilmYirenReq.URL, WarMovie.WarFilmYirenReq);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilmYirenItem.URL, WarMovie.WarFilmYirenItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarSelectActor.URL, WarMovie.WarSelectActor);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.FilmInfBtn.URL, WarMovie.FilmInfBtn);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarSelectActorItem.URL, WarMovie.WarSelectActorItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarActorProperty.URL, WarMovie.WarActorProperty);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarActorSelectTip.URL, WarMovie.WarActorSelectTip);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarActorItem.URL, WarMovie.WarActorItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarSelectFilmType.URL, WarMovie.WarSelectFilmType);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilmTypeSelectItem.URL, WarMovie.WarFilmTypeSelectItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarNotice.URL, WarMovie.WarNotice);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarYRProficiency.URL, WarMovie.WarYRProficiency);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.FilmProgressBlue.URL, WarMovie.FilmProgressBlue);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarActorProficiencyItem.URL, WarMovie.WarActorProficiencyItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilmSQView.URL, WarMovie.WarFilmSQView);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarActor160.URL, WarMovie.WarActor160);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.FilmProgressBlue2.URL, WarMovie.FilmProgressBlue2);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.AveragePress.URL, WarMovie.AveragePress);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarSQViewItem.URL, WarMovie.WarSQViewItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarCinemaSelection.URL, WarMovie.WarCinemaSelection);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarCinemaItem.URL, WarMovie.WarCinemaItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFeedBack.URL, WarMovie.WarFeedBack);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.StarProgress.URL, WarMovie.StarProgress);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.StarProgressSmall.URL, WarMovie.StarProgressSmall);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFrreBackItem.URL, WarMovie.WarFrreBackItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarAudienceReputation.URL, WarMovie.WarAudienceReputation);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarAudienceItem.URL, WarMovie.WarAudienceItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilmShangYing.URL, WarMovie.WarFilmShangYing);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarTape.URL, WarMovie.WarTape);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarShangYingProgress.URL, WarMovie.WarShangYingProgress);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilmOverMarketInfo.URL, WarMovie.WarFilmOverMarketInfo);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilmJiesuan.URL, WarMovie.WarFilmJiesuan);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.ProgressYellow.URL, WarMovie.ProgressYellow);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.ProgressBlue.URL, WarMovie.ProgressBlue);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarGoodsItem.URL, WarMovie.WarGoodsItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.ShareBtn.URL, WarMovie.ShareBtn);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarPeopleFaceItem.URL, WarMovie.WarPeopleFaceItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.GoodsItem.URL, WarMovie.GoodsItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarContinueRewardItem.URL, WarMovie.WarContinueRewardItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarCityItem.URL, WarMovie.WarCityItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarEndingIncome.URL, WarMovie.WarEndingIncome);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.ConfirmBtn2.URL, WarMovie.ConfirmBtn2);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarEndIncomeItem.URL, WarMovie.WarEndIncomeItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilmYRShow.URL, WarMovie.WarFilmYRShow);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarCurrentMarketInfo.URL, WarMovie.WarCurrentMarketInfo);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarMarketPeople.URL, WarMovie.WarMarketPeople);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarXKHuifu.URL, WarMovie.WarXKHuifu);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarBtn.URL, WarMovie.WarBtn);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarXukezhengOver.URL, WarMovie.WarXukezhengOver);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarMain.URL, WarMovie.WarMain);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilmMoveShow.URL, WarMovie.WarFilmMoveShow);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarActorItemShow.URL, WarMovie.WarActorItemShow);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.Warjiaojuan.URL, WarMovie.Warjiaojuan);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarTip.URL, WarMovie.WarTip);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarTipKuang.URL, WarMovie.WarTipKuang);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilmSQ.URL, WarMovie.WarFilmSQ);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarTargetSucces.URL, WarMovie.WarTargetSucces);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarTargetFailed.URL, WarMovie.WarTargetFailed);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarTargetFailItem.URL, WarMovie.WarTargetFailItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilmLiuxing.URL, WarMovie.WarFilmLiuxing);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilmSYPF.URL, WarMovie.WarFilmSYPF);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarBgCloseBtn.URL, WarMovie.WarBgCloseBtn);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.ConfirmCostBtn.URL, WarMovie.ConfirmCostBtn);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarInfBtn.URL, WarMovie.WarInfBtn);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarActorShowItem.URL, WarMovie.WarActorShowItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarJiesuanNum.URL, WarMovie.WarJiesuanNum);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.BG.URL, WarMovie.BG);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.BG2.URL, WarMovie.BG2);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.Touxiang44.URL, WarMovie.Touxiang44);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.Touxiang80.URL, WarMovie.Touxiang80);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.Touxiang160.URL, WarMovie.Touxiang160);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarActor80.URL, WarMovie.WarActor80);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarActor44.URL, WarMovie.WarActor44);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.Touxiang80noMask.URL, WarMovie.Touxiang80noMask);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarActor80noMask.URL, WarMovie.WarActor80noMask);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarActor120.URL, WarMovie.WarActor120);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.Touxiang120.URL, WarMovie.Touxiang120);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarjiaojuanPinPu.URL, WarMovie.WarjiaojuanPinPu);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.NoticeIcon.URL, WarMovie.NoticeIcon);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarAttributeUpTip.URL, WarMovie.WarAttributeUpTip);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarYRNoticeItem.URL, WarMovie.WarYRNoticeItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.MinDialog.URL, WarMovie.MinDialog);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.ShwoMinDialog.URL, WarMovie.ShwoMinDialog);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarGoldProgressBar.URL, WarMovie.WarGoldProgressBar);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.ZhuIcon.URL, WarMovie.ZhuIcon);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.TargetSiccesItem.URL, WarMovie.TargetSiccesItem);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarMoveTextHide.URL, WarMovie.WarMoveTextHide);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.SQFlash.URL, WarMovie.SQFlash);
                fairygui.UIObjectFactory.setPackageItemExtension(WarMovie.WarFilmingGoldEffect.URL, WarMovie.WarFilmingGoldEffect);
            };
            return WarMovieBinder;
        }());
        WarMovie.WarMovieBinder = WarMovieBinder;
    })(WarMovie = fgui.WarMovie || (fgui.WarMovie = {}));
})(fgui || (fgui = {}));
//# sourceMappingURL=WarMovieBinder.js.map